spring:
  application:
    name: crypto_investment
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_investment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true

rate-limiter:
  capacity: 10
  refill-tokens: 10
  refill-duration: 1

supported-cryptos: BTC,ETH,DOGE,LTC
